server:
  port: 8080

spring:
  datasource:
    dynamic:
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/tmvp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
          username: techmg
          password: Tech@123++**
        slave:
          url: jdbc:mysql://localhost:3306/tmvp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
          username: techmg
          password: Tech@123++**

logging:
  level:
    com.icbc.sh.techmg: DEBUG
